stages:
  - build
  - test
  - deploy

build-centos-job:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - ./main
  tags:
    - centos
  artifacts:
    paths:
      - "build/"

test-centos-job:
  stage: test
  dependencies: 
    - build-centos-job
  script:
    - cd build
    - ctest
  tags:
    - centos

deploy-centos-job:
  stage: deploy
  dependencies: 
    - build-centos-job
  script:
    - cd build
    - cmake --install . --prefix . --config Release
  tags:
    - centos
  artifacts:
    paths:
      - "matrix_calc/"
