stages:
  - build
  - test
  - package
  - package_test
  - deploy

.standart_package_test:
  stage: package_test
  script:
    - tspp_calc test/test_suite/valid.txt -f

.standart_build:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - make
  artifacts:
    name: artifact-${CI_PROJECT_NAME}-${CI_PIPELINE_ID}-${CI_JOB_NAME}
    paths:
      - "build/"
    expire_in: 10 minutes

.standart_test:
  stage: test
  script:
    - cd build
    - ./tests --gtest_output=xml:test_results.xml
    - valgrind ./tests
    - cppcheck ../src
  artifacts:
    reports:
      junit: build/test_results.xml
    expire_in: 10 minutes

build-centos-job:
  extends:
    .standart_build
  tags:
    - centos

build-ubuntu-job:
  extends:
    .standart_build
  tags:
    - ubuntu

test-centos-job:
  extends:
    .standart_test
  dependencies: 
    - build-centos-job
  tags:
    - centos
  needs:
    - job: build-centos-job

test-ubuntu-job:
  extends:
    .standart_test
  dependencies: 
    - build-ubuntu-job
  tags:
    - ubuntu
  needs:
    - job: build-ubuntu-job

doc-job:
  stage: package 
  script:
    - apt update
    - apt install doxygen-latex texlive-lang-cyrillic doxygen -y
    - doxygen Doxyfile
    - tar -cf doc/html.tar doc/html
    - cd doc/latex
    - make
    - cd ../../
  artifacts:
    name: artifact-${CI_PROJECT_NAME}-${CI_PIPELINE_ID}-${CI_JOB_NAME}
    paths:
      - doc/html.tar
      - doc/latex/refman.pdf
    expire_in: 10 minutes
  tags:
    - ubuntu

package-ubuntu-job:
  stage: package
  script:
    - mkdir -p pkg-ubuntu
    - cd build
    - cpack -G DEB
    - mv *.deb ../pkg-ubuntu/
  needs:
    - job: test-ubuntu-job
    - job: build-ubuntu-job
  dependencies:
    - build-ubuntu-job

  artifacts:
    name: artifact-${CI_PROJECT_NAME}-${CI_PIPELINE_ID}-${CI_JOB_NAME}
    paths:
      - pkg-ubuntu/
    expire_in: 10 minutes
  tags:
    - ubuntu

package-centos-job:
  stage: package
  script:
    - mkdir -p pkg-centos
    - cd build
    - cpack -G RPM
    - mv *.rpm ../pkg-centos/
  needs:
    - job: test-centos-job
    - job: build-centos-job
  dependencies:
    - build-centos-job

  artifacts:
    name: artifact-${CI_PROJECT_NAME}-${CI_PIPELINE_ID}-${CI_JOB_NAME}
    paths:
      - pkg-centos/
    expire_in: 30 minutes
  tags:
    - centos

package-test-ubuntu-job:
  extends:
    .standart_package_test
  before_script:
    #установка пакета
    - dpkg -i pkg-ubuntu/*.deb || true
    #проверка установки
    - dpkg-deb -c pkg-ubuntu/tspp_calc-1.1-Linux.deb
    - dpkg -l | grep tspp_calc || echo "Пакет не найден"
    - dpkg -L tspp_calc || echo "Файлы не найдены"

  needs:
    - job: package-ubuntu-job
  dependencies:
    - package-ubuntu-job
  tags:
    - ubuntu

package-test-centos-job:
  extends:
    .standart_package_test
  before_script:
    # установка пакета
    - rpm -i pkg-centos/*.rpm || true
    # проверка установки
    - rpm -q tspp_calc || echo "Пакет не найден"
    - rpm -ql tspp_calc || echo "Файлы не найдены"

  needs:
    - job: package-centos-job
  dependencies:
    - package-centos-job
  tags:
    - centos

deploy-job:
  stage: deploy
  script:
    - echo "Upload artifacts"
  needs:
    - doc-job
    - package-ubuntu-job
    - package-centos-job
    - package-test-ubuntu-job
    - package-test-centos-job
  dependencies:
    - doc-job
    - package-ubuntu-job
    - package-centos-job
  artifacts:
    name: artifact-${CI_PROJECT_NAME}-${CI_PIPELINE_ID}-${CI_JOB_NAME}
    paths:
      - pkg-centos/
      - pkg-ubuntu/
      - doc
    expire_in: 6 months
  when: on_success
  tags:
    - ubuntu

  
