stages:
  - build
  - test
  - package
  - deploy

.standart_build:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - make
  artifacts:
    paths:
      - "build/"
    expire_in: 10 minutes

.standart_test:
  stage: test
  script:
    - cd build
    - ./tests --gtest_output=xml:test_results.xml
    - valgrind ./tests
    - cppcheck ../src
  artifacts:
    paths:
      - build/test_results.xml
    reports:
      junit: build/test_results.xml
    expire_in: 10 minutes

build-centos-job:
  extends:
    .standart_build
  tags:
    - centos

build-ubuntu-job:
  extends:
    .standart_build
  tags:
    - ubuntu

test-centos-job:
  extends:
    .standart_test
  dependencies: 
    - build-centos-job
  tags:
    - centos
  needs:
    - job: build-centos-job

test-ubuntu-job:
  extends:
    .standart_test
  dependencies: 
    - build-ubuntu-job
  tags:
    - ubuntu
  needs:
    - job: build-ubuntu-job

doc-job:
  stage: build
  script:
    - apt update
    - apt install doxygen-latex texlive-lang-cyrillic doxygen -y
    - doxygen Doxyfile
    - tar -cf doc/html.tar doc/html
    - cd doc/latex
    - make
    - cd ../../
  artifacts:
    paths:
      - doc/html.tar
      - doc/latex/refman.pdf
    expire_in: 10 minutes
  tags:
    - ubuntu

package-ubuntu-job:
  stage: package
  script:
    - mkdir -p pkg-ubuntu
    - cd build
    - cpack -G DEB
    - mv *.deb ../pkg-ubuntu/
  needs:
    - job: test-ubuntu-job
    - job: build-ubuntu-job
  dependencies:
    - build-ubuntu-job

  artifacts:
    paths:
      - pkg-ubuntu/
    expire_in: 10 minutes
  tags:
    - ubuntu

package-centos-job:
  stage: package
  script:
    - mkdir -p pkg-centos
    - cd build
    - cpack -G RPM
    - mv *.rpm ../pkg-centos/
  needs:
    - job: test-centos-job
    - job: build-centos-job
  dependencies:
    - build-centos-job

  artifacts:
    paths:
      - pkg-centos/
    expire_in: 30 minutes
  tags:
    - centos

deploy-job:
  stage: deploy
  script:
    - echo "Upload artifacts"
  needs:
    - doc-job
    - package-ubuntu-job
    - package-centos-job
  dependencies:
    - doc-job
    - package-ubuntu-job
    - package-centos-job
  artifacts:
    paths:
      - pkg-centos/
      - pkg-ubuntu/
      - doc
  when: on_success
  tags:
    - ubuntu

  
