stages:
  - build
  - test

.standart_build:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
  artifacts:
    paths:
      - "build/"
    expire_in: 10 minutes

.standart_test:
  stage: test
  script:
    - cd build
    - ctest


build-centos-job:
  extends:
    .standart_build
  tags:
    - centos

build-ubuntu-job:
  extends:
    .standart_build
  tags:
    - ubuntu

test-centos-job:
  extends:
    .standart_test
  dependencies: 
    - build-centos-job
  script:
    - cd build
    - ctest
  tags:
    - centos

test-ubuntu-job:
  extends:
    .standart_test
  dependencies: 
    - build-ubuntu-job
  tags:
    - ubuntu
