stages:
  - build
  - test
  - release

build-centos-job:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - ./main
  tags:
    - centos
  artifacts:
    paths:
      - "build/"

test-centos-job:
  stage: test
  dependencies: 
    - build-centos-job
  script:
    - cd build
    - ctest
  tags:
    - centos

release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG                  # Run this job when a tag is created manually
  script:
    - echo "Running the release job."
  release:
    tag_name: $CI_COMMIT_TAG
    name: 'Release $CI_COMMIT_TAG'
    description: 'Release created using the release-cli.'
